/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VideoStudioRouteImport } from './routes/video-studio'
import { Route as TryOnRouteImport } from './routes/try-on'
import { Route as StyloRouteImport } from './routes/stylo'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PoseStudioRouteImport } from './routes/pose-studio'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoStudioIndexRouteImport } from './routes/video-studio.index'
import { Route as TryOnIndexRouteImport } from './routes/try-on.index'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as PricingIndexRouteImport } from './routes/pricing.index'
import { Route as PoseStudioIndexRouteImport } from './routes/pose-studio.index'
import { Route as VideoStudioResultRouteImport } from './routes/video-studio.result'
import { Route as TryOnResultRouteImport } from './routes/try-on.result'
import { Route as StoreStoreIdRouteImport } from './routes/store.$storeId'
import { Route as PricingSuccessRouteImport } from './routes/pricing.success'
import { Route as PricingPaymentRouteImport } from './routes/pricing.payment'
import { Route as PricingCheckoutRouteImport } from './routes/pricing.checkout'
import { Route as PoseStudioResultRouteImport } from './routes/pose-studio.result'
import { Route as OnboardingTryOnRouteImport } from './routes/onboarding.try-on'
import { Route as OnboardingStyloRouteImport } from './routes/onboarding.stylo'
import { Route as OnboardingSaveRouteImport } from './routes/onboarding.save'
import { Route as OnboardingFeaturesRouteImport } from './routes/onboarding.features'
import { Route as StoreProductProductIdRouteImport } from './routes/store.product.$productId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoStudioRoute = VideoStudioRouteImport.update({
  id: '/video-studio',
  path: '/video-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TryOnRoute = TryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const StyloRoute = StyloRouteImport.update({
  id: '/stylo',
  path: '/stylo',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PoseStudioRoute = PoseStudioRouteImport.update({
  id: '/pose-studio',
  path: '/pose-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoStudioIndexRoute = VideoStudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideoStudioRoute,
} as any)
const TryOnIndexRoute = TryOnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TryOnRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PricingRoute,
} as any)
const PoseStudioIndexRoute = PoseStudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PoseStudioRoute,
} as any)
const VideoStudioResultRoute = VideoStudioResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => VideoStudioRoute,
} as any)
const TryOnResultRoute = TryOnResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => TryOnRoute,
} as any)
const StoreStoreIdRoute = StoreStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => StoreRoute,
} as any)
const PricingSuccessRoute = PricingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => PricingRoute,
} as any)
const PricingPaymentRoute = PricingPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => PricingRoute,
} as any)
const PricingCheckoutRoute = PricingCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PricingRoute,
} as any)
const PoseStudioResultRoute = PoseStudioResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => PoseStudioRoute,
} as any)
const OnboardingTryOnRoute = OnboardingTryOnRouteImport.update({
  id: '/onboarding/try-on',
  path: '/onboarding/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStyloRoute = OnboardingStyloRouteImport.update({
  id: '/onboarding/stylo',
  path: '/onboarding/stylo',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSaveRoute = OnboardingSaveRouteImport.update({
  id: '/onboarding/save',
  path: '/onboarding/save',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFeaturesRoute = OnboardingFeaturesRouteImport.update({
  id: '/onboarding/features',
  path: '/onboarding/features',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreProductProductIdRoute = StoreProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pose-studio': typeof PoseStudioRouteWithChildren
  '/pricing': typeof PricingRouteWithChildren
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/store': typeof StoreRouteWithChildren
  '/stylo': typeof StyloRoute
  '/try-on': typeof TryOnRouteWithChildren
  '/video-studio': typeof VideoStudioRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/onboarding/features': typeof OnboardingFeaturesRoute
  '/onboarding/save': typeof OnboardingSaveRoute
  '/onboarding/stylo': typeof OnboardingStyloRoute
  '/onboarding/try-on': typeof OnboardingTryOnRoute
  '/pose-studio/result': typeof PoseStudioResultRoute
  '/pricing/checkout': typeof PricingCheckoutRoute
  '/pricing/payment': typeof PricingPaymentRoute
  '/pricing/success': typeof PricingSuccessRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/try-on/result': typeof TryOnResultRoute
  '/video-studio/result': typeof VideoStudioResultRoute
  '/pose-studio/': typeof PoseStudioIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/store/': typeof StoreIndexRoute
  '/try-on/': typeof TryOnIndexRoute
  '/video-studio/': typeof VideoStudioIndexRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/stylo': typeof StyloRoute
  '/welcome': typeof WelcomeRoute
  '/onboarding/features': typeof OnboardingFeaturesRoute
  '/onboarding/save': typeof OnboardingSaveRoute
  '/onboarding/stylo': typeof OnboardingStyloRoute
  '/onboarding/try-on': typeof OnboardingTryOnRoute
  '/pose-studio/result': typeof PoseStudioResultRoute
  '/pricing/checkout': typeof PricingCheckoutRoute
  '/pricing/payment': typeof PricingPaymentRoute
  '/pricing/success': typeof PricingSuccessRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/try-on/result': typeof TryOnResultRoute
  '/video-studio/result': typeof VideoStudioResultRoute
  '/pose-studio': typeof PoseStudioIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/store': typeof StoreIndexRoute
  '/try-on': typeof TryOnIndexRoute
  '/video-studio': typeof VideoStudioIndexRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pose-studio': typeof PoseStudioRouteWithChildren
  '/pricing': typeof PricingRouteWithChildren
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/store': typeof StoreRouteWithChildren
  '/stylo': typeof StyloRoute
  '/try-on': typeof TryOnRouteWithChildren
  '/video-studio': typeof VideoStudioRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/onboarding/features': typeof OnboardingFeaturesRoute
  '/onboarding/save': typeof OnboardingSaveRoute
  '/onboarding/stylo': typeof OnboardingStyloRoute
  '/onboarding/try-on': typeof OnboardingTryOnRoute
  '/pose-studio/result': typeof PoseStudioResultRoute
  '/pricing/checkout': typeof PricingCheckoutRoute
  '/pricing/payment': typeof PricingPaymentRoute
  '/pricing/success': typeof PricingSuccessRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/try-on/result': typeof TryOnResultRoute
  '/video-studio/result': typeof VideoStudioResultRoute
  '/pose-studio/': typeof PoseStudioIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/store/': typeof StoreIndexRoute
  '/try-on/': typeof TryOnIndexRoute
  '/video-studio/': typeof VideoStudioIndexRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credits'
    | '/home'
    | '/login'
    | '/notifications'
    | '/pose-studio'
    | '/pricing'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/splash'
    | '/store'
    | '/stylo'
    | '/try-on'
    | '/video-studio'
    | '/welcome'
    | '/onboarding/features'
    | '/onboarding/save'
    | '/onboarding/stylo'
    | '/onboarding/try-on'
    | '/pose-studio/result'
    | '/pricing/checkout'
    | '/pricing/payment'
    | '/pricing/success'
    | '/store/$storeId'
    | '/try-on/result'
    | '/video-studio/result'
    | '/pose-studio/'
    | '/pricing/'
    | '/store/'
    | '/try-on/'
    | '/video-studio/'
    | '/store/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credits'
    | '/home'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/splash'
    | '/stylo'
    | '/welcome'
    | '/onboarding/features'
    | '/onboarding/save'
    | '/onboarding/stylo'
    | '/onboarding/try-on'
    | '/pose-studio/result'
    | '/pricing/checkout'
    | '/pricing/payment'
    | '/pricing/success'
    | '/store/$storeId'
    | '/try-on/result'
    | '/video-studio/result'
    | '/pose-studio'
    | '/pricing'
    | '/store'
    | '/try-on'
    | '/video-studio'
    | '/store/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/credits'
    | '/home'
    | '/login'
    | '/notifications'
    | '/pose-studio'
    | '/pricing'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/splash'
    | '/store'
    | '/stylo'
    | '/try-on'
    | '/video-studio'
    | '/welcome'
    | '/onboarding/features'
    | '/onboarding/save'
    | '/onboarding/stylo'
    | '/onboarding/try-on'
    | '/pose-studio/result'
    | '/pricing/checkout'
    | '/pricing/payment'
    | '/pricing/success'
    | '/store/$storeId'
    | '/try-on/result'
    | '/video-studio/result'
    | '/pose-studio/'
    | '/pricing/'
    | '/store/'
    | '/try-on/'
    | '/video-studio/'
    | '/store/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreditsRoute: typeof CreditsRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PoseStudioRoute: typeof PoseStudioRouteWithChildren
  PricingRoute: typeof PricingRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SplashRoute: typeof SplashRoute
  StoreRoute: typeof StoreRouteWithChildren
  StyloRoute: typeof StyloRoute
  TryOnRoute: typeof TryOnRouteWithChildren
  VideoStudioRoute: typeof VideoStudioRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  OnboardingFeaturesRoute: typeof OnboardingFeaturesRoute
  OnboardingSaveRoute: typeof OnboardingSaveRoute
  OnboardingStyloRoute: typeof OnboardingStyloRoute
  OnboardingTryOnRoute: typeof OnboardingTryOnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-studio': {
      id: '/video-studio'
      path: '/video-studio'
      fullPath: '/video-studio'
      preLoaderRoute: typeof VideoStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try-on': {
      id: '/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof TryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylo': {
      id: '/stylo'
      path: '/stylo'
      fullPath: '/stylo'
      preLoaderRoute: typeof StyloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pose-studio': {
      id: '/pose-studio'
      path: '/pose-studio'
      fullPath: '/pose-studio'
      preLoaderRoute: typeof PoseStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-studio/': {
      id: '/video-studio/'
      path: '/'
      fullPath: '/video-studio/'
      preLoaderRoute: typeof VideoStudioIndexRouteImport
      parentRoute: typeof VideoStudioRoute
    }
    '/try-on/': {
      id: '/try-on/'
      path: '/'
      fullPath: '/try-on/'
      preLoaderRoute: typeof TryOnIndexRouteImport
      parentRoute: typeof TryOnRoute
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pose-studio/': {
      id: '/pose-studio/'
      path: '/'
      fullPath: '/pose-studio/'
      preLoaderRoute: typeof PoseStudioIndexRouteImport
      parentRoute: typeof PoseStudioRoute
    }
    '/video-studio/result': {
      id: '/video-studio/result'
      path: '/result'
      fullPath: '/video-studio/result'
      preLoaderRoute: typeof VideoStudioResultRouteImport
      parentRoute: typeof VideoStudioRoute
    }
    '/try-on/result': {
      id: '/try-on/result'
      path: '/result'
      fullPath: '/try-on/result'
      preLoaderRoute: typeof TryOnResultRouteImport
      parentRoute: typeof TryOnRoute
    }
    '/store/$storeId': {
      id: '/store/$storeId'
      path: '/$storeId'
      fullPath: '/store/$storeId'
      preLoaderRoute: typeof StoreStoreIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/pricing/success': {
      id: '/pricing/success'
      path: '/success'
      fullPath: '/pricing/success'
      preLoaderRoute: typeof PricingSuccessRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/payment': {
      id: '/pricing/payment'
      path: '/payment'
      fullPath: '/pricing/payment'
      preLoaderRoute: typeof PricingPaymentRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/checkout': {
      id: '/pricing/checkout'
      path: '/checkout'
      fullPath: '/pricing/checkout'
      preLoaderRoute: typeof PricingCheckoutRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pose-studio/result': {
      id: '/pose-studio/result'
      path: '/result'
      fullPath: '/pose-studio/result'
      preLoaderRoute: typeof PoseStudioResultRouteImport
      parentRoute: typeof PoseStudioRoute
    }
    '/onboarding/try-on': {
      id: '/onboarding/try-on'
      path: '/onboarding/try-on'
      fullPath: '/onboarding/try-on'
      preLoaderRoute: typeof OnboardingTryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/stylo': {
      id: '/onboarding/stylo'
      path: '/onboarding/stylo'
      fullPath: '/onboarding/stylo'
      preLoaderRoute: typeof OnboardingStyloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/save': {
      id: '/onboarding/save'
      path: '/onboarding/save'
      fullPath: '/onboarding/save'
      preLoaderRoute: typeof OnboardingSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/features': {
      id: '/onboarding/features'
      path: '/onboarding/features'
      fullPath: '/onboarding/features'
      preLoaderRoute: typeof OnboardingFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/product/$productId': {
      id: '/store/product/$productId'
      path: '/product/$productId'
      fullPath: '/store/product/$productId'
      preLoaderRoute: typeof StoreProductProductIdRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface PoseStudioRouteChildren {
  PoseStudioResultRoute: typeof PoseStudioResultRoute
  PoseStudioIndexRoute: typeof PoseStudioIndexRoute
}

const PoseStudioRouteChildren: PoseStudioRouteChildren = {
  PoseStudioResultRoute: PoseStudioResultRoute,
  PoseStudioIndexRoute: PoseStudioIndexRoute,
}

const PoseStudioRouteWithChildren = PoseStudioRoute._addFileChildren(
  PoseStudioRouteChildren,
)

interface PricingRouteChildren {
  PricingCheckoutRoute: typeof PricingCheckoutRoute
  PricingPaymentRoute: typeof PricingPaymentRoute
  PricingSuccessRoute: typeof PricingSuccessRoute
  PricingIndexRoute: typeof PricingIndexRoute
}

const PricingRouteChildren: PricingRouteChildren = {
  PricingCheckoutRoute: PricingCheckoutRoute,
  PricingPaymentRoute: PricingPaymentRoute,
  PricingSuccessRoute: PricingSuccessRoute,
  PricingIndexRoute: PricingIndexRoute,
}

const PricingRouteWithChildren =
  PricingRoute._addFileChildren(PricingRouteChildren)

interface StoreRouteChildren {
  StoreStoreIdRoute: typeof StoreStoreIdRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreProductProductIdRoute: typeof StoreProductProductIdRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreStoreIdRoute: StoreStoreIdRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreProductProductIdRoute: StoreProductProductIdRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface TryOnRouteChildren {
  TryOnResultRoute: typeof TryOnResultRoute
  TryOnIndexRoute: typeof TryOnIndexRoute
}

const TryOnRouteChildren: TryOnRouteChildren = {
  TryOnResultRoute: TryOnResultRoute,
  TryOnIndexRoute: TryOnIndexRoute,
}

const TryOnRouteWithChildren = TryOnRoute._addFileChildren(TryOnRouteChildren)

interface VideoStudioRouteChildren {
  VideoStudioResultRoute: typeof VideoStudioResultRoute
  VideoStudioIndexRoute: typeof VideoStudioIndexRoute
}

const VideoStudioRouteChildren: VideoStudioRouteChildren = {
  VideoStudioResultRoute: VideoStudioResultRoute,
  VideoStudioIndexRoute: VideoStudioIndexRoute,
}

const VideoStudioRouteWithChildren = VideoStudioRoute._addFileChildren(
  VideoStudioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreditsRoute: CreditsRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PoseStudioRoute: PoseStudioRouteWithChildren,
  PricingRoute: PricingRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SplashRoute: SplashRoute,
  StoreRoute: StoreRouteWithChildren,
  StyloRoute: StyloRoute,
  TryOnRoute: TryOnRouteWithChildren,
  VideoStudioRoute: VideoStudioRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  OnboardingFeaturesRoute: OnboardingFeaturesRoute,
  OnboardingSaveRoute: OnboardingSaveRoute,
  OnboardingStyloRoute: OnboardingStyloRoute,
  OnboardingTryOnRoute: OnboardingTryOnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
